@startuml
'https://plantuml.com/class-diagram

interface Cloneable

class QuestionBank {
    + clone()
}
QuestionBank -up..|> Cloneable

class QuestionBankController
QuestionBank --* QuestionBankController

@enduml